### PR TITLE
feat add rust-void

### PR DESCRIPTION
**Pull request by Starains320**
the source for the Rust void crate

Log: add rust-void
Issue: https://github.com/deepin-community/sig-deepin-sysdev-team/issues/136

### CODE REVIEW

**Comment by Starains320** [comment]
@chenchongbiao 老师您好，obs已通过，请检查pr

**Comment by Starains320** [comment]
@chenchongbiao 老师您好，请检查一下pr

**Comment by Starains320** [comment]
@chenchongbiao 老师您好，请检查一下pr

**Review by chenchongbiao — APPROVED** [review]

**Pull request merged**
